### ISSUE TITLE
Directory hard coded

### ISSUE THREAD

**Issue by dekz** [akdubya/rbytes#2]
Traceback (most recent call last):
  File "/usr/local/bin/node-waf", line 16, in <module>
    Scripting.prepare(t, os.getcwd(), VERSION, wafdir)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 145, in prepare
    prepare_impl(t, cwd, ver, wafdir)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 135, in prepare_impl
    main()
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 188, in main
    fun(ctx)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 386, in build
    return build_impl(bld)
  File "/usr/local/bin/../lib/node/wafadmin/Scripting.py", line 405, in build_impl
    bld.compile()
  File "/usr/local/bin/../lib/node/wafadmin/Build.py", line 268, in compile
    os.chdir(self.bldnode.abspath())
OSError: [Errno 2] No such file or directory: '/home/lex/dev/projects/rbytes/build'

**Comment by briangriffey** [comment]
same problem.

**Comment by tbranyen** [comment]
Pull from github and npm install from inside that directory, fixed it for me

**Comment by diversario** [comment]
Same here, fails with
    OSError: [Errno 2] No such file or directory: '/home/lex/dev/projects/rbytes/build'

**Comment by ljantos** [comment]
same problem on Ubuntu here, but not on Mac OS

**Comment by NebuPookins** [comment]
Same issue here, also on Ubuntu.

**Comment by ppetermair** [comment]
Since the source of rbytes doesn't contain any "home/lex" strings, I doubt that it is a rbytes issue.
I tried it on Ubuntu and Debian and both experience this problem .. on a Mac it works fine though. The NPM and node.js sources also don't contain any "home/lex" strings, so I would guess that it is most likely some problem with a library from Debian/Ubutnu (python?).

btw: tbranyen's workaround worked for me too

**Comment by NebuPookins** [comment]
It's a strange issue. If installing from the git repo fixes it, then presumably it has nothing to do with the OS libraries, but I can't find any other explanation.

**Comment by tbranyen** [comment]
GitHub and NPM are not necessarily 1:1 its quite possible the author pushed broken code to NPM and working code to GitHub...

**Comment by diversario** [comment]
Package in NPM repo contains lines in `\package\build\c4che\default.cache.py`:

```
LIBDIR = '/home/lex/.node_libraries'
NODE_PATH = '/home/lex/.node_libraries'
```

Maybe that's it.

**Comment by akdubya** [comment]
Yeah NPM is doing some weird shit here w.r.t. propagating the local cache. I'll see what I can do about fixing the package.

**Comment by amper5and** [comment]
I'm still getting this error when installing from npm due to /home/lex/dev/projects/rbytes/build being hard-coded inside. Unfortunately, I can't pull from github, because my hosting provider uses npm to resolve dependencies. 

Will this be fixed soon?

**Comment by akdubya** [comment]
I just forced a rebuild of the package and tested everything locally from another user. Let me know if this works for you.

**Comment by tbranyen** [comment]
Seems fixed on my end.

**Comment by amper5and** [comment]
It's fixed. Thanks, akdubya.
