### ISSUE TITLE
npm install fail in win 7

### ISSUE THREAD

**Issue by zanhsieh** [akdubya/rbytes#5]
C:\xampp\htdocs\mpgs_sockjs>npm install rbytes
npm http GET https://registry.npmjs.org/rbytes
npm http 200 https://registry.npmjs.org/rbytes

> rbytes@0.0.2 install C:\xampp\htdocs\mpgs_sockjs\node_modules\rbytes
> node-waf configure build

'node-waf' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! error installing rbytes@0.0.2

npm ERR! rbytes@0.0.2 install: `node-waf configure build`
npm ERR! `cmd "/c" "node-waf configure build"` failed with 1
npm ERR!
npm ERR! Failed at the rbytes@0.0.2 install script.
npm ERR! This is most likely a problem with the rbytes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls rbytes
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files (x86)\nodejs\\node.exe" "C:\Program File
s (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "rbytes"
npm ERR! cwd C:\xampp\htdocs\mpgs_sockjs
npm ERR! node -v v0.6.11
npm ERR! npm -v 1.1.1
npm ERR! code ELIFECYCLE
npm ERR! message rbytes@0.0.2 install: `node-waf configure build`
npm ERR! message `cmd "/c" "node-waf configure build"` failed with 1
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\xampp\htdocs\mpgs_sockjs\npm-debug.log
npm not ok

C:\xampp\htdocs\mpgs_sockjs>

**Comment by lexander** [comment]
This is due to an error npm's handling of optionalDependencies. sockjs has an optionalDependency on rbytes. Upgrade to version 1.1.41 or higher of npm and it should work. See @isaacs comment in https://github.com/sockjs/sockjs-node/issues/80
